#!/bin/sh

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
        - id: check-yaml
          args: [--allow-multiple-documents]
        - id: no-commit-to-branch
          args: [--branch, staging, --branch, master]
        - id: debug-statements
        - id: end-of-file-fixer
    
    - repo: https://github.com/PyCQA/isort
      rev: 5.12.0
      hooks:
      - id: isort
        args: [--profile=black, --gitignore]
    
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
      - id: black
        args: [--check]

    - repo: https://github.com/PyCQA/autoflake
      rev: v2.0.1
      hooks:
      - id: autoflake
        args: [-r, --remove-all-unused-imports, --remove-unused-variables, --in-place]
